### ISSUE TITLE
Simulating & testing race conditions

### ISSUE THREAD

**Issue by younes-io** [younes-io/booking-manager-api#5]
This is being discussed in [this issue](https://github.com/dubzzz/fast-check/issues/2780).

So far, there are two elements :
* When a call is made to `/api/v1/reservation` inside a `fast-check` block, the API returns a `415` => encoding issue; I have been able to avoid this by a workaround described [here](https://github.com/jsdom/jsdom/issues/2060#issuecomment-751259273)
* With the option `{ numRuns : 1}`, I get a `404` => not expected because the mock should return a reservation object that would avoid the 404 error

**Comment by younes-io** [comment]
Stack trace of the encoding issue:

```
Exception has occurred: Error: Encoding not recognized: 'utf8' (searched as: 'utf8')
  at Object.getCodec (/home/dev/project/booking-manager-api/node_modules/iconv-lite/lib/index.js:106:23)
    at Object.getDecoder (/home/dev/project/booking-manager-api/node_modules/iconv-lite/lib/index.js:127:23)
    at getDecoder (/home/dev/project/booking-manager-api/node_modules/raw-body/index.js:46:18)
    at readStream (/home/dev/project/booking-manager-api/node_modules/raw-body/index.js:187:15)
    at executor (/home/dev/project/booking-manager-api/node_modules/raw-body/index.js:113:5)
    at new Promise (<anonymous>)
    at getRawBody (/home/dev/project/booking-manager-api/node_modules/raw-body/index.js:112:10)
    at AsyncFunction.Object.<anonymous>.module.exports [as json] (/home/dev/project/booking-manager-api/node_modules/co-body/lib/json.js:39:21)
    at bodyParser (/home/dev/project/booking-manager-api/node_modules/koa-bodyparser/index.js:85:25)
    at parseBody (/home/dev/project/booking-manager-api/node_modules/koa-bodyparser/index.js:100:26)
```
